// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD6KUpqucTYJJnoTPK45G-YOUmStlID4is',
    appId: '1:366027234839:web:5236a400db3439ccb64652',
    messagingSenderId: '366027234839',
    projectId: 'r-s-eats',
    authDomain: 'r-s-eats.firebaseapp.com',
    storageBucket: 'r-s-eats.appspot.com',
    measurementId: 'G-Z79R75DZZG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCI7y0_g_u79yqOXXFZsqCTSNbBR2XWjMg',
    appId: '1:366027234839:android:c8e87d1438b0621eb64652',
    messagingSenderId: '366027234839',
    projectId: 'r-s-eats',
    storageBucket: 'r-s-eats.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyADHjEBgdWP8ZfOSxT4nmdi5VUnV1wrl_Q',
    appId: '1:366027234839:ios:360f21e1ca679c7cb64652',
    messagingSenderId: '366027234839',
    projectId: 'r-s-eats',
    storageBucket: 'r-s-eats.appspot.com',
    iosBundleId: 'com.example.mobileApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyADHjEBgdWP8ZfOSxT4nmdi5VUnV1wrl_Q',
    appId: '1:366027234839:ios:360f21e1ca679c7cb64652',
    messagingSenderId: '366027234839',
    projectId: 'r-s-eats',
    storageBucket: 'r-s-eats.appspot.com',
    iosBundleId: 'com.example.mobileApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD6KUpqucTYJJnoTPK45G-YOUmStlID4is',
    appId: '1:366027234839:web:b9a74e8394113553b64652',
    messagingSenderId: '366027234839',
    projectId: 'r-s-eats',
    authDomain: 'r-s-eats.firebaseapp.com',
    storageBucket: 'r-s-eats.appspot.com',
    measurementId: 'G-MCF4MEDNYS',
  );
}
